# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chord.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_Chord(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

    def detect_n(self, n, str_):
        self.n = n
        self.state = str_
        self.combox_c1.setCurrentText(str_)

    def setupUi(self, Chord):
        Chord.setObjectName("Chord")
        Chord.resize(551, 176)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(192, 192, 192))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 192, 192))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 192, 192))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 192, 192))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 192, 192))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 192, 192))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 192, 192))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 192, 192))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 192, 192))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        Chord.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(16)
        Chord.setFont(font)
        Chord.setStyleSheet("background-color: rgb(192, 192, 192);")
        self.chord_save = QtWidgets.QPushButton(Chord)
        self.chord_save.setGeometry(QtCore.QRect(450, 140, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setUnderline(True)
        self.chord_save.setFont(font)
        self.chord_save.setStyleSheet("background-image: url(:/image/1.PNG);")
        self.chord_save.setObjectName("chord_save")
        self.combox_c1 = QtWidgets.QComboBox(Chord)
        self.combox_c1.setGeometry(QtCore.QRect(40, 70, 471, 22))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(13)
        self.combox_c1.setFont(font)
        self.combox_c1.setStyleSheet("border-image: url(:/image/1.PNG);")
        self.combox_c1.setObjectName("combox_c1")
        self.combox_c1.addItem("")
        self.combox_c1.addItem("")
        self.combox_c1.addItem("")
        self.combox_c1.addItem("")
        self.combox_c1.addItem("")
        self.combox_c1.addItem("")
        self.combox_c1.addItem("")
        self.combox_c1.addItem("")
        self.chord_help = QtWidgets.QPushButton(Chord)
        self.chord_help.setGeometry(QtCore.QRect(380, 140, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setUnderline(True)
        self.chord_help.setFont(font)
        self.chord_help.setStyleSheet("background-image: url(:/image/1.PNG);")
        self.chord_help.setObjectName("chord_help")

        self.retranslateUi(Chord)
        QtCore.QMetaObject.connectSlotsByName(Chord)

        self.combox_c1.currentIndexChanged.connect(self.change_)

        # help
        self.chord_help.clicked.connect(self.edit_chord_button)

    def retranslateUi(self, Chord):
        _translate = QtCore.QCoreApplication.translate
        Chord.setWindowTitle(_translate("Chord", "Chord"))
        self.chord_save.setText(_translate("Chord", "    Save    "))
        self.combox_c1.setItemText(0, _translate("Chord", "-"))
        self.combox_c1.setItemText(1, _translate("Chord", "Am"))
        self.combox_c1.setItemText(2, _translate("Chord", "C"))
        self.combox_c1.setItemText(3, _translate("Chord", "Dm"))
        self.combox_c1.setItemText(4, _translate("Chord", "Em"))
        self.combox_c1.setItemText(5, _translate("Chord", "F"))
        self.combox_c1.setItemText(6, _translate("Chord", "G"))
        self.combox_c1.setItemText(7, _translate("Chord", "G7"))
        self.chord_help.setText(_translate("Chord", "    Help    "))

    def change_(self):
        self.state = self.combox_c1.currentText()

    def keyPressEvent(self, e):
        if e.key() == QtCore.Qt.Key_Escape:
            self.close()

    def edit_chord_button(self):
        msg = QMessageBox()
        msg.setWindowTitle("?")
        msg.setText("選擇此小節要演奏的和弦~")
        msg.setIcon(QMessageBox.Question)
        x = msg.exec_()    


import images


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Chord = Ui_Chord()
    Chord.show()
    sys.exit(app.exec_())
