# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'filename.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os

class Ui_Form(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

    def setupUi(self, Form):
        Form.setObjectName("Import")
        Form.resize(314*2, 153*2)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(100*2, 60*2, 171*2, 20*2))
        self.lineEdit.setObjectName("lineEdit")
        self.Import_button = QtWidgets.QPushButton(Form)
        self.Import_button.setGeometry(QtCore.QRect(120*2, 200, 75*2, 20*2))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setUnderline(True)
        self.Import_button.setFont(font)
        self.Import_button.setObjectName("Import_button")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30*2, 60*2, 71*2, 21*2))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.label_2 = QtWidgets.QLabel(self)
        self.label_2.setGeometry(QtCore.QRect(160, 60, 450, 50))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        _translate = QtCore.QCoreApplication.translate
        self.label_2.setText(_translate("Import", " Please enter absolute path."))



    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        path = os.path.abspath("main_window.py")
        Form.setWindowTitle(_translate("Import", "Import"))
        self.Import_button.setText(_translate("Import", "Import"))
        self.label.setText(_translate("Import", "Enter File Name"))
        self.lineEdit.setText(path[:-14])

    def return_name(self):
        return self.lineEdit.text()

    def initial(self):
        _translate = QtCore.QCoreApplication.translate
        self.label_2.setGeometry(QtCore.QRect(160, 60, 450, 50))
        self.label_2.setText(_translate("Import", " Please enter absolute path."))  
        self.label_2.setStyleSheet("color: black;")


    def keyPressEvent(self, e):
        if e.key() == QtCore.Qt.Key_Escape:
            self.close()

class choose_Form(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

    def setupUi(self, Form):
        Form.setObjectName("Import")
        Form.resize(314*2, 153*2)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(100*2, 60*2, 171*2, 20*2))
        self.lineEdit.setObjectName("lineEdit")
        self.Import_button = QtWidgets.QPushButton(Form)
        self.Import_button.setGeometry(QtCore.QRect(120*2, 200, 75*2, 20*2))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setUnderline(True)
        self.Import_button.setFont(font)
        self.Import_button.setObjectName("Import_button")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30*2, 60*2, 71*2, 21*2))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.label_2 = QtWidgets.QLabel(self)
        self.label_2.setGeometry(QtCore.QRect(100, 60, 450, 50))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        _translate = QtCore.QCoreApplication.translate
        self.label_2.setText(_translate("Import", "Please enter absolute path of the music file."))



    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        path = os.path.abspath("main_window.py")
        Form.setWindowTitle(_translate("Import", "Import"))
        self.Import_button.setText(_translate("Import", "Play!!"))
        self.label.setText(_translate("Import", "Enter File Name"))
        self.lineEdit.setText(path[:-14])

    def return_name(self):
        return self.lineEdit.text()

    def initial(self):
        _translate = QtCore.QCoreApplication.translate
        self.label_2.setGeometry(QtCore.QRect(100, 60, 450, 50))
        self.label_2.setText(_translate("Import", "Please enter absolute path of the music file."))
        self.label_2.setStyleSheet("color: black;")


    def keyPressEvent(self, e):
        if e.key() == QtCore.Qt.Key_Escape:
            self.close()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = choose_Form()
    Form.show()
    sys.exit(app.exec_())
