# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import piano, chord, drum, filename, import_list
import pygame, time
import os

class Ui_MuSiC_CrEaToR(QtWidgets.QMainWindow):
    # set up __init__
    def __init__(self):
        super(Ui_MuSiC_CrEaToR, self).__init__()
        self.setupUi(self)
        self.piano_dict = {"piano1":0, "piano2":1, "piano3":2, "piano4":3, "piano5":4, "piano6":5, "piano7":6, "piano8":7}
        self.chord_dict = {"Chord1":0, "Chord2":1, "Chord3":2, "Chord4":3, "Chord5":4, "Chord6":5, "Chord7":6, "Chord8":7}
        self.drum_dict = {"drum1":0, "drum2":1, "drum3":2, "drum4":3, "drum5":4, "drum6":5, "drum7":6, "drum8":7}
        self.piano_matrix = ["-"] * 64
        self.chord_matrix = ["-"] * 8
        self.drum_matrix = ["-"] * 64
        self.bpm = 120
        
    def setupUi(self, MuSiC_CrEaToR):
        MuSiC_CrEaToR.setObjectName("MuSiC_CrEaToR")
        MuSiC_CrEaToR.resize(557*2, 331*2)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        MuSiC_CrEaToR.setFont(font)
        MuSiC_CrEaToR.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MuSiC_CrEaToR.setAutoFillBackground(False)
        MuSiC_CrEaToR.setStyleSheet("background-image: url(:/image/cover.jpg);")
        self.centralwidget = QtWidgets.QWidget(MuSiC_CrEaToR)
        self.centralwidget.setObjectName("centralwidget")
        self.piano1 = QtWidgets.QPushButton(self.centralwidget)
        self.piano1.setGeometry(QtCore.QRect(140*2, 80*2, 51*2, 21*2))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.piano1.setFont(font)
        self.piano1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.piano1.setAutoFillBackground(False)
        self.piano1.setStyleSheet("background-image: url(:/image/1.PNG);")
        self.piano1.setObjectName("piano1")
        self.piano2 = QtWidgets.QPushButton(self.centralwidget)
        self.piano2.setGeometry(QtCore.QRect(190*2, 80*2, 51*2, 21*2))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.piano2.setFont(font)
        self.piano2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.piano2.setAutoFillBackground(False)
        self.piano2.setStyleSheet("background-image: url(:/image/1.PNG);")
        self.piano2.setObjectName("piano2")
        self.piano3 = QtWidgets.QPushButton(self.centralwidget)
        self.piano3.setGeometry(QtCore.QRect(240*2, 80*2, 51*2, 21*2))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.piano3.setFont(font)
        self.piano3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.piano3.setAutoFillBackground(False)
        self.piano3.setStyleSheet("background-image: url(:/image/1.PNG);")
        self.piano3.setObjectName("piano3")
        self.piano4 = QtWidgets.QPushButton(self.centralwidget)
        self.piano4.setGeometry(QtCore.QRect(290*2, 80*2, 51*2, 21*2))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.piano4.setFont(font)
        self.piano4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.piano4.setAutoFillBackground(False)
        self.piano4.setStyleSheet("background-image: url(:/image/1.PNG);")
        self.piano4.setObjectName("piano4")
        self.piano8 = QtWidgets.QPushButton(self.centralwidget)
        self.piano8.setGeometry(QtCore.QRect(490*2, 80*2, 51*2, 21*2))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.piano8.setFont(font)
        self.piano8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.piano8.setAutoFillBackground(False)
        self.piano8.setStyleSheet("background-image: url(:/image/1.PNG);")
        self.piano8.setObjectName("piano8")
        self.piano6 = QtWidgets.QPushButton(self.centralwidget)
        self.piano6.setGeometry(QtCore.QRect(390*2, 80*2, 51*2, 21*2))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.piano6.setFont(font)
        self.piano6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.piano6.setAutoFillBackground(False)
        self.piano6.setStyleSheet("background-image: url(:/image/1.PNG);")
        self.piano6.setObjectName("piano6")
        self.piano7 = QtWidgets.QPushButton(self.centralwidget)
        self.piano7.setGeometry(QtCore.QRect(440*2, 80*2, 51*2, 21*2))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.piano7.setFont(font)
        self.piano7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.piano7.setAutoFillBackground(False)
        self.piano7.setStyleSheet("background-image: url(:/image/1.PNG);")
        self.piano7.setObjectName("piano7")
        self.piano5 = QtWidgets.QPushButton(self.centralwidget)
        self.piano5.setGeometry(QtCore.QRect(340*2, 80*2, 51*2, 21*2))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.piano5.setFont(font)
        self.piano5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.piano5.setAutoFillBackground(False)
        self.piano5.setStyleSheet("background-image: url(:/image/1.PNG);")
        self.piano5.setObjectName("piano5")
        self.piano = QtWidgets.QPushButton(self.centralwidget)
        self.piano.setGeometry(QtCore.QRect(20*2, 80*2, 111*2, 21*2))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(False)
        self.piano.setFont(font)
        self.piano.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.piano.setAutoFillBackground(False)
        self.piano.setStyleSheet("background-image: url(:/image/1.PNG);")
        self.piano.setObjectName("piano")
        self.Chord1 = QtWidgets.QPushButton(self.centralwidget)
        self.Chord1.setGeometry(QtCore.QRect(140*2, 120*2, 51*2, 21*2))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.Chord1.setFont(font)
        self.Chord1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Chord1.setStyleSheet("background-image: url(:/image/2.JPG);")
        self.Chord1.setObjectName("Chord1")
        self.Chord2 = QtWidgets.QPushButton(self.centralwidget)
        self.Chord2.setGeometry(QtCore.QRect(190*2, 120*2, 51*2, 21*2))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.Chord2.setFont(font)
        self.Chord2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Chord2.setStyleSheet("background-image: url(:/image/2.JPG);")
        self.Chord2.setObjectName("Chord2")
        self.Chord3 = QtWidgets.QPushButton(self.centralwidget)
        self.Chord3.setGeometry(QtCore.QRect(240*2, 120*2, 51*2, 21*2))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.Chord3.setFont(font)
        self.Chord3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Chord3.setStyleSheet("background-image: url(:/image/2.JPG);")
        self.Chord3.setObjectName("Chord3")
        self.Chord4 = QtWidgets.QPushButton(self.centralwidget)
        self.Chord4.setGeometry(QtCore.QRect(290*2, 120*2, 51*2, 21*2))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.Chord4.setFont(font)
        self.Chord4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Chord4.setStyleSheet("background-image: url(:/image/2.JPG);")
        self.Chord4.setObjectName("Chord4")
        self.Chord5 = QtWidgets.QPushButton(self.centralwidget)
        self.Chord5.setGeometry(QtCore.QRect(340*2, 120*2, 51*2, 21*2))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.Chord5.setFont(font)
        self.Chord5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Chord5.setStyleSheet("background-image: url(:/image/2.JPG);")
        self.Chord5.setObjectName("Chord5")
        self.Chord6 = QtWidgets.QPushButton(self.centralwidget)
        self.Chord6.setGeometry(QtCore.QRect(390*2, 120*2, 51*2, 21*2))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.Chord6.setFont(font)
        self.Chord6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Chord6.setStyleSheet("background-image: url(:/image/2.JPG);")
        self.Chord6.setObjectName("Chord6")
        self.Chord7 = QtWidgets.QPushButton(self.centralwidget)
        self.Chord7.setGeometry(QtCore.QRect(440*2, 120*2, 51*2, 21*2))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.Chord7.setFont(font)
        self.Chord7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Chord7.setStyleSheet("background-image: url(:/image/2.JPG);")
        self.Chord7.setObjectName("Chord7")
        self.Chord8 = QtWidgets.QPushButton(self.centralwidget)
        self.Chord8.setGeometry(QtCore.QRect(490*2, 120*2, 51*2, 21*2))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.Chord8.setFont(font)
        self.Chord8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Chord8.setStyleSheet("background-image: url(:/image/2.JPG);")
        self.Chord8.setObjectName("Chord8")
        self.Chord = QtWidgets.QPushButton(self.centralwidget)
        self.Chord.setGeometry(QtCore.QRect(20*2, 120*2, 111*2, 21*2))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.Chord.setFont(font)
        self.Chord.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Chord.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Chord.setStyleSheet("background-image: url(:/image/2.JPG);")
        self.Chord.setObjectName("Chord")
        self.drum8 = QtWidgets.QPushButton(self.centralwidget)
        self.drum8.setGeometry(QtCore.QRect(490*2, 160*2, 51*2, 21*2))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.drum8.setFont(font)
        self.drum8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.drum8.setAutoFillBackground(False)
        self.drum8.setStyleSheet("background-image: url(:/image/1.PNG);")
        self.drum8.setObjectName("drum8")
        self.drum6 = QtWidgets.QPushButton(self.centralwidget)
        self.drum6.setGeometry(QtCore.QRect(390*2, 160*2, 51*2, 21*2))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.drum6.setFont(font)
        self.drum6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.drum6.setAutoFillBackground(False)
        self.drum6.setStyleSheet("background-image: url(:/image/1.PNG);")
        self.drum6.setObjectName("drum6")
        self.drum7 = QtWidgets.QPushButton(self.centralwidget)
        self.drum7.setGeometry(QtCore.QRect(440*2, 160*2, 51*2, 21*2))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.drum7.setFont(font)
        self.drum7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.drum7.setAutoFillBackground(False)
        self.drum7.setStyleSheet("background-image: url(:/image/1.PNG);")
        self.drum7.setObjectName("drum7")
        self.drum2 = QtWidgets.QPushButton(self.centralwidget)
        self.drum2.setGeometry(QtCore.QRect(190*2, 160*2, 51*2, 21*2))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.drum2.setFont(font)
        self.drum2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.drum2.setAutoFillBackground(False)
        self.drum2.setStyleSheet("background-image: url(:/image/1.PNG);")
        self.drum2.setObjectName("drum2")
        self.drum4 = QtWidgets.QPushButton(self.centralwidget)
        self.drum4.setGeometry(QtCore.QRect(290*2, 160*2, 51*2, 21*2))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.drum4.setFont(font)
        self.drum4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.drum4.setAutoFillBackground(False)
        self.drum4.setStyleSheet("background-image: url(:/image/1.PNG);")
        self.drum4.setObjectName("drum4")
        self.drum5 = QtWidgets.QPushButton(self.centralwidget)
        self.drum5.setGeometry(QtCore.QRect(340*2, 160*2, 51*2, 21*2))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.drum5.setFont(font)
        self.drum5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.drum5.setAutoFillBackground(False)
        self.drum5.setStyleSheet("background-image: url(:/image/1.PNG);")
        self.drum5.setObjectName("drum5")
        self.drum3 = QtWidgets.QPushButton(self.centralwidget)
        self.drum3.setGeometry(QtCore.QRect(240*2, 160*2, 51*2, 21*2))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.drum3.setFont(font)
        self.drum3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.drum3.setAutoFillBackground(False)
        self.drum3.setStyleSheet("background-image: url(:/image/1.PNG);")
        self.drum3.setObjectName("drum3")
        self.drum1 = QtWidgets.QPushButton(self.centralwidget)
        self.drum1.setGeometry(QtCore.QRect(140*2, 160*2, 51*2, 21*2))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.drum1.setFont(font)
        self.drum1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.drum1.setAutoFillBackground(False)
        self.drum1.setStyleSheet("background-image: url(:/image/1.PNG);")
        self.drum1.setObjectName("drum1")
        self.drum = QtWidgets.QPushButton(self.centralwidget)
        self.drum.setGeometry(QtCore.QRect(20*2, 160*2, 111*2, 21*2))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(False)
        self.drum.setFont(font)
        self.drum.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.drum.setAutoFillBackground(False)
        self.drum.setStyleSheet("background-image: url(:/image/1.PNG);")
        self.drum.setObjectName("drum")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(390*2, 270*2, 71*2, 21*2))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setUnderline(True)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-image: url(:/image/1.PNG);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(470*2, 270*2, 71*2, 21*2))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setUnderline(True)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-image: url(:/image/1.PNG);")
        self.pushButton_2.setObjectName("pushButton_2")
        MuSiC_CrEaToR.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MuSiC_CrEaToR)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 557, 18))
        self.menubar.setObjectName("menubar")
        self.menuFunction = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        self.menuFunction.setFont(font)
        self.menuFunction.setTearOffEnabled(False)
        self.menuFunction.setTitle("")
        self.menuFunction.setObjectName("menuFunction")
        MuSiC_CrEaToR.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MuSiC_CrEaToR)
        self.statusbar.setObjectName("statusbar")
        MuSiC_CrEaToR.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFunction.menuAction())

        self.import_button = QtWidgets.QPushButton(self.centralwidget)
        self.import_button.setGeometry(QtCore.QRect(620, 270*2, 71*2, 21*2))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setUnderline(True)
        self.import_button.setFont(font)
        self.import_button.setStyleSheet("background-image: url(:/image/1.PNG);")
        self.import_button.setObjectName("import_button")

        self.retranslateUi(MuSiC_CrEaToR)
        QtCore.QMetaObject.connectSlotsByName(MuSiC_CrEaToR)
        
        # button event - piano
        self.piano_bar = piano.piano_bar()
        self.piano1.clicked.connect(self.detect)
        self.piano1.clicked.connect(self.piano_bar.show)

        self.piano2.clicked.connect(self.detect)
        self.piano2.clicked.connect(self.piano_bar.show)
        
        self.piano3.clicked.connect(self.detect)
        self.piano3.clicked.connect(self.piano_bar.show)

        self.piano4.clicked.connect(self.detect)
        self.piano4.clicked.connect(self.piano_bar.show)

        self.piano5.clicked.connect(self.detect)
        self.piano5.clicked.connect(self.piano_bar.show)

        self.piano6.clicked.connect(self.detect)
        self.piano6.clicked.connect(self.piano_bar.show)

        self.piano7.clicked.connect(self.detect)
        self.piano7.clicked.connect(self.piano_bar.show)

        self.piano8.clicked.connect(self.detect)
        self.piano8.clicked.connect(self.piano_bar.show)

        # button event - chord
        self.chord_bar = chord.Ui_Chord()
        self.Chord1.clicked.connect(self.detect)
        self.Chord1.clicked.connect(self.chord_bar.show)

        self.Chord2.clicked.connect(self.detect)
        self.Chord2.clicked.connect(self.chord_bar.show)

        self.Chord3.clicked.connect(self.detect)
        self.Chord3.clicked.connect(self.chord_bar.show)

        self.Chord4.clicked.connect(self.detect)
        self.Chord4.clicked.connect(self.chord_bar.show)

        self.Chord5.clicked.connect(self.detect)
        self.Chord5.clicked.connect(self.chord_bar.show)

        self.Chord6.clicked.connect(self.detect)
        self.Chord6.clicked.connect(self.chord_bar.show)

        self.Chord7.clicked.connect(self.detect)
        self.Chord7.clicked.connect(self.chord_bar.show)

        self.Chord8.clicked.connect(self.detect)
        self.Chord8.clicked.connect(self.chord_bar.show)

        # button event - drum
        self.drum_bar = drum.Ui_Drum()
        self.drum1.clicked.connect(self.detect)
        self.drum1.clicked.connect(self.drum_bar.show)

        self.drum2.clicked.connect(self.detect)
        self.drum2.clicked.connect(self.drum_bar.show)

        self.drum3.clicked.connect(self.detect)
        self.drum3.clicked.connect(self.drum_bar.show)

        self.drum4.clicked.connect(self.detect)
        self.drum4.clicked.connect(self.drum_bar.show)

        self.drum5.clicked.connect(self.detect)
        self.drum5.clicked.connect(self.drum_bar.show)

        self.drum6.clicked.connect(self.detect)
        self.drum6.clicked.connect(self.drum_bar.show)

        self.drum7.clicked.connect(self.detect)
        self.drum7.clicked.connect(self.drum_bar.show)

        self.drum8.clicked.connect(self.detect)
        self.drum8.clicked.connect(self.drum_bar.show)

        # save event
        self.piano_bar.piano_save.clicked.connect(self.call_save)
        self.chord_bar.chord_save.clicked.connect(self.call_save)
        self.drum_bar.drum_save.clicked.connect(self.call_save)

        # preview event
        self.pushButton.clicked.connect(self.Preview)

        # Export event
        self.setfilename = filename.Ui_Form()
        self.pushButton_2.clicked.connect(self.setfilename.show)
        self.pushButton_2.clicked.connect(self.setfilename.label_2.hide)
        self.setfilename.OK_button.clicked.connect(self.setname)

        # Import event
        self.import_file = import_list.Ui_Form()
        self.import_button.clicked.connect(self.import_file.show)
        self.import_button.clicked.connect(self.import_file.initial)
        self.import_file.Import_button.clicked.connect(self.fileimporting)

        # help
        self.piano.clicked.connect(self.main_piano_button)
        self.Chord.clicked.connect(self.main_chord_button)
        self.drum.clicked.connect(self.main_drum_button)

    def call_save(self):
        send = self.sender()
        name = send.objectName()
        if name[0] == "p":
            self.save(self.piano_bar)
        elif name[0] == "c":
            self.save(self.chord_bar)
        elif name[0] == 'd':
            self.save(self.drum_bar)
    
    def save(self, obj):
        if obj == self.piano_bar:
            for i in range(8):
                self.piano_matrix[8*obj.n+i] = obj.state[i]
            self.piano_bar.close()

        elif obj == self.chord_bar:
            self.chord_matrix[obj.n] = obj.state
            self.chord_bar.close()

        elif obj == self.drum_bar:
            for i in range(8):
                self.drum_matrix[8*obj.n+i] = obj.state[i]
            self.drum_bar.close()

    def retranslateUi(self, MuSiC_CrEaToR):
        _translate = QtCore.QCoreApplication.translate
        MuSiC_CrEaToR.setWindowTitle(_translate("MuSiC_CrEaToR", "MainWindow"))
        self.piano1.setText(_translate("MuSiC_CrEaToR", "Edit"))
        self.piano2.setText(_translate("MuSiC_CrEaToR", "Edit"))
        self.piano3.setText(_translate("MuSiC_CrEaToR", "Edit"))
        self.piano4.setText(_translate("MuSiC_CrEaToR", "Edit"))
        self.piano8.setText(_translate("MuSiC_CrEaToR", "Edit"))
        self.piano6.setText(_translate("MuSiC_CrEaToR", "Edit"))
        self.piano7.setText(_translate("MuSiC_CrEaToR", "Edit"))
        self.piano5.setText(_translate("MuSiC_CrEaToR", "Edit"))
        self.piano.setText(_translate("MuSiC_CrEaToR", "Piano"))
        self.Chord1.setText(_translate("MuSiC_CrEaToR", "Edit"))
        self.Chord2.setText(_translate("MuSiC_CrEaToR", "Edit"))
        self.Chord3.setText(_translate("MuSiC_CrEaToR", "Edit"))
        self.Chord4.setText(_translate("MuSiC_CrEaToR", "Edit"))
        self.Chord5.setText(_translate("MuSiC_CrEaToR", "Edit"))
        self.Chord6.setText(_translate("MuSiC_CrEaToR", "Edit"))
        self.Chord7.setText(_translate("MuSiC_CrEaToR", "Edit"))
        self.Chord8.setText(_translate("MuSiC_CrEaToR", "Edit"))
        self.Chord.setText(_translate("MuSiC_CrEaToR", "Chord"))
        self.drum8.setText(_translate("MuSiC_CrEaToR", "Edit"))
        self.drum6.setText(_translate("MuSiC_CrEaToR", "Edit"))
        self.drum7.setText(_translate("MuSiC_CrEaToR", "Edit"))
        self.drum2.setText(_translate("MuSiC_CrEaToR", "Edit"))
        self.drum4.setText(_translate("MuSiC_CrEaToR", "Edit"))
        self.drum5.setText(_translate("MuSiC_CrEaToR", "Edit"))
        self.drum3.setText(_translate("MuSiC_CrEaToR", "Edit"))
        self.drum1.setText(_translate("MuSiC_CrEaToR", "Edit"))
        self.drum.setText(_translate("MuSiC_CrEaToR", "Drum"))
        self.pushButton.setText(_translate("MuSiC_CrEaToR", "Preview"))
        self.pushButton_2.setText(_translate("MuSiC_CrEaToR", "Export"))
        self.import_button.setText(_translate("MuSiC_CrEaToR", "Import"))
    
    def detect(self):
        sender = self.sender()
        name = sender.objectName()
        if name[0] == "p":
            n = self.piano_dict[name]
            self.piano_bar.detect_n(n)
            list_ = self.piano_matrix[n*8:n*8+8]
            self.piano_bar.set_up_default(list_)
        elif name[0] == "C":
            n = self.chord_dict[name]
            self.chord_bar.detect_n(n, self.chord_matrix[n])
        elif name[0] == "d":
            n = self.drum_dict[name]
            self.drum_bar.detect_n(n)
            list_ = self.drum_matrix[n*8:n*8+8]
            self.drum_bar.set_up_default(list_)

    def Preview(self):
        #plus
        pygame.init()
        pygame.mixer.init()
        pygame.mixer.music.set_volume(1.0)

        for i in range(64):
            if self.piano_matrix[i] != "-":
                if not pygame.mixer.Channel(0).get_busy():
                    pygame.mixer.Channel(0).play(pygame.mixer.Sound(f'sound/piano/{self.piano_matrix[i]}.wav'))

            if i % 8 == 0 and self.chord_matrix[i//8] != "-":
                if not pygame.mixer.Channel(1).get_busy():
                    pygame.mixer.Channel(1).play(pygame.mixer.Sound(f'sound/chord/{self.chord_matrix[i//8]}.wav'))

            if self.drum_matrix[i] != "-":
                if not pygame.mixer.Channel(2).get_busy():
                    pygame.mixer.Channel(2).play(pygame.mixer.Sound(f'sound/drum/{self.drum_matrix[i]}.wav'))
            

            time.sleep(self.bpm / 8 / 60)

            if i < 63:
                if pygame.mixer.Channel(0).get_busy() and self.piano_matrix[i+1] != "-":
                    pygame.mixer.Channel(0).stop()
                
                if pygame.mixer.Channel(2).get_busy() and self.drum_matrix[i+1] != "-":
                    pygame.mixer.Channel(2).stop()

                if pygame.mixer.Channel(1).get_busy() and (i+1) % 8 == 0:
                    pygame.mixer.Channel(1).stop()

    def fileimporting(self):
        file = self.import_file.return_name()
        is_file = os.path.isfile(file)
        if not is_file:
            self.import_file.close()
            _translate = QtCore.QCoreApplication.translate
            self.import_file.label_2.setGeometry(QtCore.QRect(225, 60, 450, 50))
            self.import_file.label_2.setText(_translate("Import", "There is no file!"))
            self.import_file.label_2.setStyleSheet("color: red;")
            self.import_file.show()
        else:
            with open(file, "r") as f:
                temp = f.read()
            temp = temp.split("\n")
            self.piano_matrix = [i for i in temp[0].split(",")]
            self.chord_matrix = [i for i in temp[1].split(",")]
            self.drum_matrix = [i for i in temp[2].split(",")]
            self.import_file.close()

    def setname(self):
        file_name = self.setfilename.return_name() + ".txt"
        is_file = os.path.isfile(file_name)
        if is_file:
            self.setfilename.close()
            self.setfilename.label_2.show()
            self.setfilename.show()
        else:
            self.setfilename.label_2.hide()
            with open(file_name, "x") as f:
                for i in range(64):
                    if i == 63:
                        f.write(self.piano_matrix[i] + "\n")
                    else:
                        f.write(self.piano_matrix[i] + ",")
                for i in range(8):
                    if i == 7:
                        f.write(self.chord_matrix[i] + "\n")
                    else:
                        f.write(self.chord_matrix[i] + ",")
                for i in range(64):
                    if i == 63:
                        f.write(self.drum_matrix[i] + "\n")
                    else:
                        f.write(self.drum_matrix[i] + ",")
            self.setfilename.close()
            

    def keyPressEvent(self, e):
        if e.key() == QtCore.Qt.Key_Escape:
            self.close()

    def main_piano_button(self):
        msg = QMessageBox()
        msg.setWindowTitle("?")
        msg.setText("由鋼琴奏主旋律，遊戲中的按鍵會跟隨此音軌的節奏~每個Edit代表一個小節")
        msg.setIcon(QMessageBox.Question)
        x = msg.exec_()

    def main_chord_button(self):
        msg = QMessageBox()
        msg.setWindowTitle("?")
        msg.setText("就和弦~每個Edit代表一個小節")
        msg.setIcon(QMessageBox.Question)
        x = msg.exec_()

    def main_drum_button(self):
        msg = QMessageBox()
        msg.setWindowTitle("?")
        msg.setText("用鼓組展現你的節奏感~每個Edit代表一個小節")
        msg.setIcon(QMessageBox.Question)
        x = msg.exec_()


import images


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MuSiC_CrEaToR = Ui_MuSiC_CrEaToR()
    MuSiC_CrEaToR.show()
    sys.exit(app.exec_())
